<a href="https://www.kaggle.com/code/hamdy20/assignment1?scriptVersionId=148028718" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd

df = pd.read_csv("/kaggle/input/home-credit-default-risk/application_train.csv")
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [2]:
#To determine which features are available in the dataset, you can simply print the column names:
features = df.columns.tolist()
features

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [3]:
#To identify the categorical features and their types (nominal, ordinal, ratio, or interval-based), you can iterate through the columns and check the unique values:
categorical_features = []

for feature in df.columns:
 unique_values = df[feature].nunique()

 if unique_values <= 5:
  categorical_features.append((feature, 'Nominal')) 
 else:
  categorical_features.append((feature, 'Ordinal'))
print(categorical_features)

[('SK_ID_CURR', 'Ordinal'), ('TARGET', 'Nominal'), ('NAME_CONTRACT_TYPE', 'Nominal'), ('CODE_GENDER', 'Nominal'), ('FLAG_OWN_CAR', 'Nominal'), ('FLAG_OWN_REALTY', 'Nominal'), ('CNT_CHILDREN', 'Ordinal'), ('AMT_INCOME_TOTAL', 'Ordinal'), ('AMT_CREDIT', 'Ordinal'), ('AMT_ANNUITY', 'Ordinal'), ('AMT_GOODS_PRICE', 'Ordinal'), ('NAME_TYPE_SUITE', 'Ordinal'), ('NAME_INCOME_TYPE', 'Ordinal'), ('NAME_EDUCATION_TYPE', 'Nominal'), ('NAME_FAMILY_STATUS', 'Ordinal'), ('NAME_HOUSING_TYPE', 'Ordinal'), ('REGION_POPULATION_RELATIVE', 'Ordinal'), ('DAYS_BIRTH', 'Ordinal'), ('DAYS_EMPLOYED', 'Ordinal'), ('DAYS_REGISTRATION', 'Ordinal'), ('DAYS_ID_PUBLISH', 'Ordinal'), ('OWN_CAR_AGE', 'Ordinal'), ('FLAG_MOBIL', 'Nominal'), ('FLAG_EMP_PHONE', 'Nominal'), ('FLAG_WORK_PHONE', 'Nominal'), ('FLAG_CONT_MOBILE', 'Nominal'), ('FLAG_PHONE', 'Nominal'), ('FLAG_EMAIL', 'Nominal'), ('OCCUPATION_TYPE', 'Ordinal'), ('CNT_FAM_MEMBERS', 'Ordinal'), ('REGION_RATING_CLIENT', 'Nominal'), ('REGION_RATING_CLIENT_W_CITY', 'Nominal'), ('WEEKDAY_APPR_PROCESS_START', 'Ordinal'), ('HOUR_APPR_PROCESS_START', 'Ordinal'), ('REG_REGION_NOT_LIVE_REGION', 'Nominal'), ('REG_REGION_NOT_WORK_REGION', 'Nominal'), ('LIVE_REGION_NOT_WORK_REGION', 'Nominal'), ('REG_CITY_NOT_LIVE_CITY', 'Nominal'), ('REG_CITY_NOT_WORK_CITY', 'Nominal'), ('LIVE_CITY_NOT_WORK_CITY', 'Nominal'), ('ORGANIZATION_TYPE', 'Ordinal'), ('EXT_SOURCE_1', 'Ordinal'), ('EXT_SOURCE_2', 'Ordinal'), ('EXT_SOURCE_3', 'Ordinal'), ('APARTMENTS_AVG', 'Ordinal'), ('BASEMENTAREA_AVG', 'Ordinal'), ('YEARS_BEGINEXPLUATATION_AVG', 'Ordinal'), ('YEARS_BUILD_AVG', 'Ordinal'), ('COMMONAREA_AVG', 'Ordinal'), ('ELEVATORS_AVG', 'Ordinal'), ('ENTRANCES_AVG', 'Ordinal'), ('FLOORSMAX_AVG', 'Ordinal'), ('FLOORSMIN_AVG', 'Ordinal'), ('LANDAREA_AVG', 'Ordinal'), ('LIVINGAPARTMENTS_AVG', 'Ordinal'), ('LIVINGAREA_AVG', 'Ordinal'), ('NONLIVINGAPARTMENTS_AVG', 'Ordinal'), ('NONLIVINGAREA_AVG', 'Ordinal'), ('APARTMENTS_MODE', 'Ordinal'), ('BASEMENTAREA_MODE', 'Ordinal'), ('YEARS_BEGINEXPLUATATION_MODE', 'Ordinal'), ('YEARS_BUILD_MODE', 'Ordinal'), ('COMMONAREA_MODE', 'Ordinal'), ('ELEVATORS_MODE', 'Ordinal'), ('ENTRANCES_MODE', 'Ordinal'), ('FLOORSMAX_MODE', 'Ordinal'), ('FLOORSMIN_MODE', 'Ordinal'), ('LANDAREA_MODE', 'Ordinal'), ('LIVINGAPARTMENTS_MODE', 'Ordinal'), ('LIVINGAREA_MODE', 'Ordinal'), ('NONLIVINGAPARTMENTS_MODE', 'Ordinal'), ('NONLIVINGAREA_MODE', 'Ordinal'), ('APARTMENTS_MEDI', 'Ordinal'), ('BASEMENTAREA_MEDI', 'Ordinal'), ('YEARS_BEGINEXPLUATATION_MEDI', 'Ordinal'), ('YEARS_BUILD_MEDI', 'Ordinal'), ('COMMONAREA_MEDI', 'Ordinal'), ('ELEVATORS_MEDI', 'Ordinal'), ('ENTRANCES_MEDI', 'Ordinal'), ('FLOORSMAX_MEDI', 'Ordinal'), ('FLOORSMIN_MEDI', 'Ordinal'), ('LANDAREA_MEDI', 'Ordinal'), ('LIVINGAPARTMENTS_MEDI', 'Ordinal'), ('LIVINGAREA_MEDI', 'Ordinal'), ('NONLIVINGAPARTMENTS_MEDI', 'Ordinal'), ('NONLIVINGAREA_MEDI', 'Ordinal'), ('FONDKAPREMONT_MODE', 'Nominal'), ('HOUSETYPE_MODE', 'Nominal'), ('TOTALAREA_MODE', 'Ordinal'), ('WALLSMATERIAL_MODE', 'Ordinal'), ('EMERGENCYSTATE_MODE', 'Nominal'), ('OBS_30_CNT_SOCIAL_CIRCLE', 'Ordinal'), ('DEF_30_CNT_SOCIAL_CIRCLE', 'Ordinal'), ('OBS_60_CNT_SOCIAL_CIRCLE', 'Ordinal'), ('DEF_60_CNT_SOCIAL_CIRCLE', 'Ordinal'), ('DAYS_LAST_PHONE_CHANGE', 'Ordinal'), ('FLAG_DOCUMENT_2', 'Nominal'), ('FLAG_DOCUMENT_3', 'Nominal'), ('FLAG_DOCUMENT_4', 'Nominal'), ('FLAG_DOCUMENT_5', 'Nominal'), ('FLAG_DOCUMENT_6', 'Nominal'), ('FLAG_DOCUMENT_7', 'Nominal'), ('FLAG_DOCUMENT_8', 'Nominal'), ('FLAG_DOCUMENT_9', 'Nominal'), ('FLAG_DOCUMENT_10', 'Nominal'), ('FLAG_DOCUMENT_11', 'Nominal'), ('FLAG_DOCUMENT_12', 'Nominal'), ('FLAG_DOCUMENT_13', 'Nominal'), ('FLAG_DOCUMENT_14', 'Nominal'), ('FLAG_DOCUMENT_15', 'Nominal'), ('FLAG_DOCUMENT_16', 'Nominal'), ('FLAG_DOCUMENT_17', 'Nominal'), ('FLAG_DOCUMENT_18', 'Nominal'), ('FLAG_DOCUMENT_19', 'Nominal'), ('FLAG_DOCUMENT_20', 'Nominal'), ('FLAG_DOCUMENT_21', 'Nominal'), ('AMT_REQ_CREDIT_BUREAU_HOUR', 'Nominal'), ('AMT_REQ_CREDIT_BUREAU_DAY', 'Ordinal'), ('AMT_REQ_CREDIT_BUREAU_WEEK', 'Ordinal'), ('AMT_REQ_CREDIT_BUREAU_MON', 'Ordinal'), ('AMT_REQ_CREDIT_BUREAU_QRT', 'Ordinal'), ('AMT_REQ_CREDIT_BUREAU_YEAR', 'Ordinal')]

In [4]:
#To identify the numerical features and their types (discrete, continuous, or timeseries-based), you canuse the following code:
numerical_features = []

for feature in df.columns:
  if df[feature].dtype in ['float64']:
    numerical_features.append((feature, 'Continuous')) 

print(numerical_features)

[('AMT_INCOME_TOTAL', 'Continuous'), ('AMT_CREDIT', 'Continuous'), ('AMT_ANNUITY', 'Continuous'), ('AMT_GOODS_PRICE', 'Continuous'), ('REGION_POPULATION_RELATIVE', 'Continuous'), ('DAYS_REGISTRATION', 'Continuous'), ('OWN_CAR_AGE', 'Continuous'), ('CNT_FAM_MEMBERS', 'Continuous'), ('EXT_SOURCE_1', 'Continuous'), ('EXT_SOURCE_2', 'Continuous'), ('EXT_SOURCE_3', 'Continuous'), ('APARTMENTS_AVG', 'Continuous'), ('BASEMENTAREA_AVG', 'Continuous'), ('YEARS_BEGINEXPLUATATION_AVG', 'Continuous'), ('YEARS_BUILD_AVG', 'Continuous'), ('COMMONAREA_AVG', 'Continuous'), ('ELEVATORS_AVG', 'Continuous'), ('ENTRANCES_AVG', 'Continuous'), ('FLOORSMAX_AVG', 'Continuous'), ('FLOORSMIN_AVG', 'Continuous'), ('LANDAREA_AVG', 'Continuous'), ('LIVINGAPARTMENTS_AVG', 'Continuous'), ('LIVINGAREA_AVG', 'Continuous'), ('NONLIVINGAPARTMENTS_AVG', 'Continuous'), ('NONLIVINGAREA_AVG', 'Continuous'), ('APARTMENTS_MODE', 'Continuous'), ('BASEMENTAREA_MODE', 'Continuous'), ('YEARS_BEGINEXPLUATATION_MODE', 'Continuous'), ('YEARS_BUILD_MODE', 'Continuous'), ('COMMONAREA_MODE', 'Continuous'), ('ELEVATORS_MODE', 'Continuous'), ('ENTRANCES_MODE', 'Continuous'), ('FLOORSMAX_MODE', 'Continuous'), ('FLOORSMIN_MODE', 'Continuous'), ('LANDAREA_MODE', 'Continuous'), ('LIVINGAPARTMENTS_MODE', 'Continuous'), ('LIVINGAREA_MODE', 'Continuous'), ('NONLIVINGAPARTMENTS_MODE', 'Continuous'), ('NONLIVINGAREA_MODE', 'Continuous'), ('APARTMENTS_MEDI', 'Continuous'), ('BASEMENTAREA_MEDI', 'Continuous'), ('YEARS_BEGINEXPLUATATION_MEDI', 'Continuous'), ('YEARS_BUILD_MEDI', 'Continuous'), ('COMMONAREA_MEDI', 'Continuous'), ('ELEVATORS_MEDI', 'Continuous'), ('ENTRANCES_MEDI', 'Continuous'), ('FLOORSMAX_MEDI', 'Continuous'), ('FLOORSMIN_MEDI', 'Continuous'), ('LANDAREA_MEDI', 'Continuous'), ('LIVINGAPARTMENTS_MEDI', 'Continuous'), ('LIVINGAREA_MEDI', 'Continuous'), ('NONLIVINGAPARTMENTS_MEDI', 'Continuous'), ('NONLIVINGAREA_MEDI', 'Continuous'), ('TOTALAREA_MODE', 'Continuous'), ('OBS_30_CNT_SOCIAL_CIRCLE', 'Continuous'), ('DEF_30_CNT_SOCIAL_CIRCLE', 'Continuous'), ('OBS_60_CNT_SOCIAL_CIRCLE', 'Continuous'), ('DEF_60_CNT_SOCIAL_CIRCLE', 'Continuous'), ('DAYS_LAST_PHONE_CHANGE', 'Continuous'), ('AMT_REQ_CREDIT_BUREAU_HOUR', 'Continuous'), ('AMT_REQ_CREDIT_BUREAU_DAY', 'Continuous'), ('AMT_REQ_CREDIT_BUREAU_WEEK', 'Continuous'), ('AMT_REQ_CREDIT_BUREAU_MON', 'Continuous'), ('AMT_REQ_CREDIT_BUREAU_QRT', 'Continuous'), ('AMT_REQ_CREDIT_BUREAU_YEAR', 'Continuous')]

In [5]:
#To identify features that contain mixed data types (numerical and alphanumeric data within the samefeature), you can iterate over the columns and check the data type of each value within the column. If there are multiple data types present, it indicates mixed data types.
mixed_features = []

for feature in df.columns:
 data_types = df[feature].apply(type)
 unique_data_types = data_types.unique()

 if len(unique_data_types) > 1:
  mixed_features.append(feature)

print(mixed_features)

['NAME_TYPE_SUITE', 'OCCUPATION_TYPE', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE']

In [6]:
#To identify features that contain blank, null, or empty values, you can use the `isnull` function along with the `sum` function to get the count of missing values in each feature.
missing_values = df.isnull().sum()
missing_features = missing_values[missing_values > 0]

print(missing_features)

AMT_ANNUITY                       12
AMT_GOODS_PRICE                  278
NAME_TYPE_SUITE                 1292
OWN_CAR_AGE                   202929
OCCUPATION_TYPE                96391
                               ...
AMT_REQ_CREDIT_BUREAU_DAY      41519
AMT_REQ_CREDIT_BUREAU_WEEK     41519
AMT_REQ_CREDIT_BUREAU_MON      41519
AMT_REQ_CREDIT_BUREAU_QRT      41519
AMT_REQ_CREDIT_BUREAU_YEAR     41519
Length: 67, dtype: int64

In [7]:
#To assess how well the sample (train dataset) represents the actual problem domain, you can compare the proportion of deaths in the train dataset to the overall proportion of deaths in the total population.
total_population = 2224
total_deaths = 1502
train_deaths = df["AMT_INCOME_TOTAL"].sum()

train_proportion = train_deaths / len(df)
actual_proportion = total_deaths / total_population

if train_proportion > actual_proportion:
 print("The train dataset over-represents deaths.")
elif train_proportion < actual_proportion:
 print("The train dataset under-represents deaths.")
else:
 print("The train dataset represents the proportion of deaths accurately.")

The train dataset over-represents deaths.

business problem
create a model that predict the capipilty of each applicant for repaying a loan